# -*- coding: utf-8 -*-
"""PyGame_project_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7OxkpaW6mQaefVN6VVS-rI46UG6Hdmy
"""

import pygame
import sys
import time
import threading

pygame.init()
window = pygame.display.set_mode((800, 600))
pygame.display.set_caption("Osiris Laboratory")


def run_pygame_window():
    """Отдельное графическое окно"""
    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

        window.fill((20, 5, 35))  # Магическая тёмно-фиолетовая тема

        # Текстовые надписи в Pygame
        font = pygame.font.SysFont("arial", 26)
        text = font.render("Osiris Laboratory — Console Gameplay Active", True, (200, 180, 255))
        window.blit(text, (50, 50))

        pygame.display.update()

    pygame.quit()


def type_text(text, delay=0.02):
    """Друкує текст постепенно, как на машинке"""
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()


class Ingredient:
    def __init__(self, name, value, description=""):
        self.name = name
        self.value = value
        self.description = description

    def __str__(self):
        return f"{self.name} ({self.value}) — {self.description}"


class Recipe:
    def __init__(self, name, ingredients, result_value, comment=""):
        self.name = name
        self.ingredients = ingredients
        self.result_value = result_value
        self.comment = comment

    def matches(self, ingredient_list):
        return sorted(self.ingredients) == sorted(ingredient_list)


class AlchemyGame:
    def __init__(self):

        self.intro_text = (
            "After his death, your grandfather, the Great Master of Illusions, "
            "Tamer of Shadows, and renowned wizard Osiris Odimus Azirizal-iu, "
            "left you his magic laboratory along with all of its equipment.\n"
            "But you have no idea how to use it...\n\n"
            "In the recipe book your grandfather left you, you see several entries "
            "for combinations of ingredients.\n"
            "However, some writing is smudged, and several pages were torn out.\n"
        )

        # Ingredients
        self.ingredients = {

            "Water": Ingredient("Water", 0.1, "The usual clear water with no scent or taste."),
            "Rose Water": Ingredient("Rose Water", 0.5, "Light pink water with floral scent."),
            "Honey": Ingredient("Honey", 4, "Sweet and sticky golden liquid."),
            "Milk": Ingredient("Milk", 9, "White opaque liquid with slightly sweet taste."),
            "Vinegar": Ingredient("Vinegar", 6, "Strong sour-smelling liquid."),

            "Sugar": Ingredient("Sugar", 7, "White crystalized sweet substance."),
            "Regular Salt": Ingredient("Regular Salt", 3, "Common white salt crystals."),
            "Sea Salt": Ingredient("Sea Salt", 50, "Rare azure salt harvested from magical seas."),

            "Bone Powder": Ingredient("Bone Powder", 80, "Crushed remains of mythical beasts.")
        }

        # Recipes
        self.recipes = [
            Recipe(
                "Clear Water",
                ["Water"],
                0.1,
                "Just a clear water. Nothing magical here."
            ),

            Recipe(
                "Bitter-sweet potion",
                ["Water", "Honey", "Vinegar"],
                16,
                "Looks drinkable. Tastes sweet-sour. No magical effects detected."
            ),

            Recipe(
                "Salty potion",
                ["Water", "Regular Salt"],
                3.1,
                "Very salty. Might be useful in cooking or rituals."
            ),

            Recipe(
                "Rosery potion",
                ["Rose Water", "Sugar"],
                11,
                "A fragrant pink potion. Slight healing properties detected."
            )
        ]

    def comment_on_recipe(self, recipe):
        type_text(f"📜 Recipe analysis: {recipe.comment}\n", delay=0.015)

    def list_ingredients(self):
        print("\nAvailable ingredients:")
        for ing in self.ingredients.values():
            print(f" - {ing}")

    def play(self):
        # Печатаем легенду постепенно
        type_text(self.intro_text, delay=0.02)

        type_text("\n=== Osiris's Secret Laboratory ===\n")
        print("Type ingredient names separated by commas.")
        print("To exit, type: exit\n")

        while True:
            self.list_ingredients()
            print("\nEnter ingredients (example: Water, Honey, Vinegar):")
            user_input = input(">>> ")

            if user_input.lower() in ["exit", "quit"]:
                print("Exiting the laboratory...")
                break

            selected = [x.strip() for x in user_input.split(",")]

            if any(ing not in self.ingredients for ing in selected):
                print("Error: One or more ingredients do not exist!")
                continue

            match = None
            for recipe in self.recipes:
                if recipe.matches(selected):
                    match = recipe
                    break

            if match:
                print(f"\n✨ You created: **{match.name}**! Power value = {match.result_value} ✨\n")
                self.comment_on_recipe(match)
            else:
                total_value = sum(self.ingredients[i].value for i in selected)
                print(f"\n??? Unknown mixture. Its energy value = {total_value}\n")


thread = threading.Thread(target=run_pygame_window, daemon=True)
thread.start()


game = AlchemyGame()
game.play()